right:
  controller_manager:
    ros__parameters:
      update_rate: 4  # Hz

      # 加载手臂位置控制器
      cartesian_position_controller:
        type: machinery_controller/MachineryController

      # 加载吸嘴控制器
      gripper_suction_controller:
        type: gripper_suction_controller/GripperSuctionController

  cartesian_position_controller:
    ros__parameters:
      cartesian_joint_name: "right/gripper_position"

  gripper_suction_controller:
    ros__parameters:
      joints:
        - "right/gripper_suction"
      interface_name: "position"
