/**:
  ros__parameters:
    video_device: "/dev/UsbCam"
    framerate: 30.0
    io_method: "mmap"
    frame_id: "camera"
    pixel_format: "yuyv"  # see usb_cam/supported_formats for list of supported formats
    av_device_format: "YUV422P"
    image_width: 640
    image_height: 480
    camera_name: "narrow_stereo"
    camera_info_url: "package://machinery_usb_cam/config/camera_info.yaml"
    brightness: -1
    contrast: -1
    saturation: -1
    sharpness: -1
    gain: -1
    auto_white_balance: true
    white_balance: 4000
    autoexposure: true
    exposure: 30
    autofocus: true
    focus: -1

# 可以使用 v4l2-ctl -d /dev/video2 --list-formats-ext 来查看USB摄像头的信息
# 输出：
#  ioctl: VIDIOC_ENUM_FMT
#      Type: Video Capture
#
#      [0]: 'YUYV' (YUYV 4:2:2)
#          Size: Discrete 640x480
#              Interval: Discrete 0.033s (30.000 fps)
#              Interval: Discrete 0.040s (25.000 fps)
#              Interval: Discrete 0.050s (20.000 fps)
#              Interval: Discrete 0.067s (15.000 fps)
#              Interval: Discrete 0.100s (10.000 fps)
#              Interval: Discrete 0.200s (5.000 fps)
