HUMAN_AI:
  - name: "machinery_chess_bringup.launch.py"
    parameters:
      serial_port_name: "/dev/MachineryA"
      namespace: "right/"
  - name: "machinery_chess_bringup.launch.py"
    parameters:
      serial_port_name: "/dev/MachineryB"
      namespace: "left/"
  - name: "cchess_person.launch.py"
    parameters: {}

AI_AI:
  - name: "machinery_chess_bringup.launch.py"
    parameters:
      serial_port_name: "/dev/MachineryA"
      namespace: "right/"
  - name: "machinery_chess_bringup.launch.py"
    parameters:
      serial_port_name: "/dev/MachineryB"
      namespace: "left/"
  - name: "cchess_rob.launch.py"
    parameters: {}
